# Generated by Django 4.1 on 2022-08-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=50)),
                ('parol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.FileField(blank=True, upload_to='')),
                ('k_haqida', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('kanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.kanal')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(blank=True, upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('kanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.kanal')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.account')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Obuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.account')),
                ('kanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.kanal')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.account')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.account')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=400)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.account')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.video')),
            ],
        ),
    ]
